apiVersion: v1
kind: Service              
metadata:
  name: product-service-lb
spec:
  type: ClusterIP       
  ports:
  - port: 80              
    targetPort: 8081        
  selector:            
    app: product-service    
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 3                                             
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  selector:
    matchLabels:
      app: product-service
      tier: product-shop-service-tier
  template:
    metadata:
      labels:
        app: product-service
        tier: product-shop-service-tier
    spec:
      containers:
      - image: codemotiontraining/cloud-product-service-final
        name: product-service
        env:
        - name: PORT
          value: "8081"
        ports:
        - containerPort: 8081
          name: product-service
---
apiVersion: v1
kind: Service              
metadata:
  name: shop-service-lb
spec:
  type: ClusterIP       
  ports:
  - port: 80              
    targetPort: 8080        
  selector:            
    app: shop-service    
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: shop-service
  labels:
    app: shop-service
spec:
  replicas: 2                                             
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  selector:
    matchLabels:
      app: shop-service
      tier: product-shop-service-tier
  template:
    metadata:
      labels:
        app: shop-service
        tier: product-shop-service-tier
    spec:
      containers:
      - image: codemotiontraining/cloud-shop-service-final
        name: shop-service
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service-lb"  
        ports:
        - containerPort: 8080
          name: shop-service
